### ISSUE TITLE
[Feature] link the contact btn to the contact page - and send the contact form data to firstore OR discord channel OR send send an email

### ISSUE THREAD

**Issue by soufyanelf** [BizTech-Morocco/mosa3ada.biztech.ma#100]
<img width="741" alt="image" src="https://github.com/BizTech-Morocco/mosa3ada.biztech.ma/assets/24813026/0e294a57-a8aa-4fc9-9d66-9864c469fe5f">

Contact page Link : https://www.mosa3ada.ma/contact

<img width="1327" alt="image" src="https://github.com/BizTech-Morocco/mosa3ada.biztech.ma/assets/24813026/ae7e9919-d904-4f6d-b327-ee149bc80bf4">

**Comment by Abdellah-Itrkine** [comment]
Can I work on this ?

**Comment by soufyanelf** [comment]
@Abdellah-Itrkine Yes sure. we already have the contact page UI.
