### ISSUE TITLE
add the redirect to the gooogle map using exact_position if exist 

### ISSUE THREAD

**Issue by soufyanelf** [BizTech-Morocco/mosa3ada.biztech.ma#13]
Format: 
{
        location: '',
        'contact ': { fb_username: '', phone_number: '', ig_username: '' },
        date: Timestamp { seconds: 1694473200, nanoseconds: 877000000 },
        needs: [ 'إغاثة', 'طعام وماء' ],
        source: '',
        exact_position: GeoPoint { _lat: 0, _long: 0 },
        details: '',
        city: ''
}

image:
<img width="296" alt="image" src="https://github.com/BizTech-Morocco/mosa3ada.biztech.ma/assets/24813026/030ed13f-d011-4045-b636-03c585dcc2b6">

**Comment by Everkers** [comment]
This one is done.
