### ISSUE TITLE
Share a help on the social media

### ISSUE THREAD

**Issue by soufyanelf** [BizTech-Morocco/mosa3ada.biztech.ma#40]
Inside a help details add a share btn to share the help in social media

<img width="386" alt="image" src="https://github.com/BizTech-Morocco/mosa3ada.biztech.ma/assets/24813026/05c5436a-b595-4b22-b09a-f12c3a635c84">

**Comment by hmweb77** [comment]
i can use react-share npm for this 
do u thinking its a good idea?

**Comment by soufyanelf** [comment]
yes you can

**Comment by hmweb77** [comment]
okey than i will work on this

**Comment by soufyanelf** [comment]
Done by @Abdellah-Itrkine
