### ISSUE TITLE
[UI] Add the header for the web version

### ISSUE THREAD

**Issue by soufyanelf** [BizTech-Morocco/mosa3ada.biztech.ma#6]
Add a header for the web version like the picture below
![image 3](https://github.com/BizTech-Morocco/mosa3ada.biztech.ma/assets/24813026/fd61b901-bfae-46a5-9071-ae140203d74f)

please use this img for the assets

![Group 8](https://github.com/BizTech-Morocco/mosa3ada.biztech.ma/assets/24813026/8f79f484-02d0-474a-9739-6ccb6c322674)

**Comment by MohamedRach** [comment]
hi, happy to work on this issue. please can someone assign it to me.

**Comment by Everkers** [comment]
> hi, happy to work on this issue. please can someone assign it to me.

Hello @MohamedRach, this issue is already taken. Could you please look at other good first issues that aren't labeled as WIP? Thank you!
