### ISSUE TITLE
Update the header in the mobile view

### ISSUE THREAD

**Issue by soufyanelf** [BizTech-Morocco/mosa3ada.biztech.ma#60]
We need to adjust the header in the mobile view to follow this design

<img width="378" alt="image" src="https://github.com/BizTech-Morocco/mosa3ada.biztech.ma/assets/24813026/8c1976f1-caa6-4409-8352-d68cd8b1ffa6">

**Comment by haiderali88g** [comment]
@soufyanelf I can help you in achieving the desired design.
Can you assign me this task?
