### ISSUE TITLE
[BUG] Change favicon.

### ISSUE THREAD

**Issue by RuthwikReddy09** [BizTech-Morocco/mosa3ada.biztech.ma#61]
The current favicon is the default vercel favicon. Change it to the logo of the application.
The current title is "Create Next App". It needs to be changed as well.

<img width="174" alt="Screenshot 2023-09-20 180814" src="https://github.com/BizTech-Morocco/mosa3ada.biztech.ma/assets/126862059/d19027bb-54b2-48e2-b4c4-cc8c9e03713b">

**Comment by soufyanelf** [comment]
The title was fixed we still need to fix favicon only
