### ISSUE TITLE
[BUG] mapbox is not displayed on staging

### ISSUE THREAD

**Issue by soufyanelf** [BizTech-Morocco/mosa3ada.biztech.ma#69]
staging.mosa3ada.ma
Branch: staging

![image](https://github.com/BizTech-Morocco/mosa3ada.biztech.ma/assets/24813026/151b1d94-7257-4ab9-bc70-e5803ef20a4c)

**Comment by soufyanelf** [comment]
@Everkers I think you need to allow the staging.mosa3ada.ma in mapbox console

**Comment by Everkers** [comment]
> @Everkers I think you need to allow the staging.mosa3ada.ma in mapbox console

Actually that's just a typo, the env name should be **NEXT_PUBLIC_MAP_BOX_ACCESS_TOKEN**

**Comment by soufyanelf** [comment]
it works Thanks
<img width="1304" alt="image" src="https://github.com/BizTech-Morocco/mosa3ada.biztech.ma/assets/24813026/7190b685-94ff-463c-a1be-a200c038817e">
