### ISSUE TITLE
[BUG] The Discord link not working 

### ISSUE THREAD

**Issue by houssam1122** [BizTech-Morocco/mosa3ada.biztech.ma#84]
**add a new discord link!** 
![Capturegdg](https://github.com/BizTech-Morocco/mosa3ada.biztech.ma/assets/111252969/f453a683-cd3c-44ec-b5e1-22251d362c97)

Good Luck !

**Comment by GD0910** [comment]
can i work on this issue ?

**Comment by soufyanelf** [comment]
Yes sure

**Comment by GD0910** [comment]
ok can u assign me for this issue under hacktoberfest2023

**Comment by GD0910** [comment]
and please send the discord link as well

**Comment by Jineshbansal** [comment]
@soufyanelf as a part of hacktober fest 2023 , I wish to contribute to your website .Please assign this issue to me

**Comment by soufyanelf** [comment]
@GD0910 sorry for my late. the discord link is https://discord.gg/F2sAjBvX

**Comment by soufyanelf** [comment]
@Jineshbansal thanks 🙏. Please pickup any issue and let me know if you need help.

**Comment by Jineshbansal** [comment]
@

> @Jineshbansal thanks 🙏. Please pickup any issue and let me know if you need help.

Thanks for support, and kindly assign me issue for hacktober fest if possible.

**Comment by soufyanelf** [comment]
All issues are part of hacktobrfest just comment the issue you want to work in.

**Comment by GD0910** [comment]
> @GD0910 sorry for my late. the discord link is https://discord.gg/F2sAjBvX

Thank you for the link 
Will update the link quickly

**Comment by GD0910** [comment]
@soufyanelf i have updated the link in readme and contributing file can you assign this under hacktoberfest-accepted tag
